export const tableData = [{
    "id":1,
    "name": "Group1",
    "serverName":"IRWS02",
    "displayName":"INTERN_201601",
    "description": "Group1",
    "active": "yes",
    "lastModified": '4/6/2018 12:17 AM',
    "scheduled": "1/15/2019 9:00 AM ",
    "status": "Running",
    "lastRun": "1/15/2019 8:00 AM",
    "integrationRun": [{
        "integrationName": "Integration1",
        "sourceConnection": "A Connection",
        "targetConnection": "Another connection",
        "active": 'yes',
        "startRun": "1/15/2019 9:00 AM ",
        "status": "Completed",
        "lastRun": "1/15/2019 8:00 AM",
        "previousStatus": "Completed",
        "payload": 10,
        "failure": 0
    },
    {
        "integrationName": "Integration1",
        "sourceConnection": "A Connection",
        "targetConnection": "Another connection",
        "active": 'yes',
        "startRun": "1/15/2019 9:00 AM ",
        "status": "Completed",
        "lastRun": "1/15/2019 8:00 AM",
        "previousStatus": "Completed",
        "payload": 10,
        "failure": 0
    }]
},
    {
        "id":2,
        "name": "Group2",
        "serverName":"IRWS02",
        "displayName":"INTERN_201601",
        "description": "Group2",
        "active": "yes",
        "lastModified": '4/6/2018 12:17 AM',
        "scheduled": "1/15/2019 9:00 AM ",
        "status": "Running",
        "lastRun": "1/15/2019 8:00 AM",
        "integrationRun": [{
            "integrationName": "Integration1",
            "sourceConnection": "A Connection",
            "targetConnection": "Another connection",
            "active": 'yes',
            "startRun": "1/15/2019 9:00 AM ",
            "status": "Completed",
            "lastRun": "1/15/2019 8:00 AM",
            "previousStatus": "Completed",
            "payload": 10,
            "failure": 0
        }]
    },
        {
            "id":3,
            "name": "Group3",
            "serverName":"IRWS02",
            "displayName":"INTERN_201601",
            "description": "Group3",
            "active": "no",
            "lastModified": '4/6/2018 12:17 AM',
            "scheduled": "1/15/2019 9:00 AM ",
            "status": "Running",
            "lastRun": "1/15/2019 8:00 AM",
            "integrationRun": [{
                "integrationName": "Integration1",
                "sourceConnection": "A Connection",
                "targetConnection": "Another connection",
                "active": 'yes',
                "startRun": "1/15/2019 9:00 AM ",
                "status": "Completed",
                "lastRun": "1/15/2019 8:00 AM",
                "previousStatus": "Completed",
                "payload": 10,
                "failure": 0
            }]
        },
            {
                "id":4,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":5,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":6,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":7,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":8,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":9,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":10,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":11,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
            ,
            {
                "id":12,
                "name": "Group4",
                "serverName":"IRWS02",
                "displayName":"INTERN_201601",
                "description": "Group1",
                "active": "yes",
                "lastModified": '4/6/2018 12:17 AM',
                "scheduled": "1/15/2019 9:00 AM ",
                "status": "Running",
                "lastRun": "1/15/2019 8:00 AM",
                "integrationRun": [{
                    "integrationName": "Integration1",
                    "sourceConnection": "A Connection",
                    "targetConnection": "Another connection",
                    "active": 'yes',
                    "startRun": "1/15/2019 9:00 AM ",
                    "status": "Completed",
                    "lastRun": "1/15/2019 8:00 AM",
                    "previousStatus": "Completed",
                    "payload": 10,
                    "failure": 0
                }]
            }
];
